# Generated by Django 4.2.27 on 2026-05-28 04:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0013_sim_phase3_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monthly salary')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Positive: the shop owes the employee (salary / credits). Negative: the employee holds cash on behalf of the shop.', max_digits=14, verbose_name='current balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('salary_accrual', 'Salary accrual'), ('sales_payment_received', 'Sales payment received'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=32, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive: shop owes employee. Negative: employee owes shop.', max_digits=14, verbose_name='amount')),
                ('salary_month', models.DateField(blank=True, help_text='First day of the month for salary accrual rows.', null=True, verbose_name='salary month')),
                ('payer_name', models.CharField(blank=True, max_length=200, verbose_name='payer name')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='phone or shipment number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_ledger_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='employees.employeeprofile', verbose_name='employee')),
                ('reference_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_ledger_entries', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'employee ledger entry',
                'verbose_name_plural': 'employee ledger entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='emp_ledger_recent_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'salary_accrual')), fields=('employee', 'salary_month'), name='emp_salary_accrual_unique_month'),
        ),
        migrations.AddConstraint(
            model_name='employeeledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'sales_payment_received')), fields=('reference_sale',), name='emp_sale_payment_unique_sale'),
        ),
    ]
