# Generated by Django 4.2.27 on 2026-05-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_expense_date_desc_idx_and_more'),
        ('employees', '0001_employee_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeledgerentry',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_ledger_entry', to='expenses.expense', verbose_name='expense'),
        ),
    ]
