# Generated by Django 4.2.30 on 2026-07-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_payment_via_employee'),
        ('employees', '0002_salary_expense_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeledgerentry',
            name='reference_customer_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_ledger_entries', to='customers.customerpayment', verbose_name='customer payment'),
        ),
        migrations.AlterField(
            model_name='employeeledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('salary_accrual', 'Salary accrual'), ('sales_payment_received', 'Sales payment received'), ('customer_payment_received', 'Customer payment received'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=32, verbose_name='type'),
        ),
        migrations.AddConstraint(
            model_name='employeeledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'customer_payment_received')), fields=('reference_customer_payment',), name='emp_cust_payment_unique_pay'),
        ),
    ]
