# Generated by Django 4.2.16 on 2026-04-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Shown in the browser tab and bookmarks. Resized automatically.', null=True, upload_to='branding/', verbose_name='favicon'),
        ),
    ]
