# Generated by Django 4.2.16 on 2026-04-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitebranding_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='site_name',
            field=models.CharField(blank=True, help_text='Displayed in the browser tab title, the sidebar header, and the login page. Leave empty to keep the default name.', max_length=120, verbose_name='site name'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short text shown under the site name in the sidebar. Leave empty to keep the default.', max_length=160, verbose_name='tagline'),
        ),
    ]
