# Generated by Django 4.2.30 on 2026-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appsettings_sales_show_employee_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='public_default_language',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='public_default_theme',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='sales_inventory_enabled',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='sales_show_refresh_phone',
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='sales_show_employee_payment',
            field=models.BooleanField(default=True, help_text='When off, the payment-to-employee option is hidden on the employee sales screen.', verbose_name='Show payment to employee on sales entry'),
        ),
    ]
