# Generated by Django 4.2.16 on 2026-04-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture shown in the topbar menu.', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
