# Generated by Django 4.2.27 on 2026-05-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stale_phone_threshold_days',
            field=models.PositiveIntegerField(default=90, help_text='Used by the “lines for disconnect” report: numbers whose last non-cancelled sale is older than this many days appear in the list.', verbose_name='stale line threshold (days)'),
        ),
    ]
