# Generated by Django 4.2.27 on 2026-05-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLineTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_key', models.CharField(db_index=True, help_text='Lowercased trimmed sale reference / phone key.', max_length=64, unique=True, verbose_name='normalized reference')),
                ('sim_identifier', models.CharField(blank=True, max_length=200, verbose_name='SIM / chip')),
                ('last_display_reference', models.CharField(blank=True, help_text='Most recent raw reference as entered on a sale.', max_length=64, verbose_name='last display reference')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='hidden from stale list')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'phone line tracking',
                'verbose_name_plural': 'phone line tracking',
            },
        ),
    ]
