# Generated by Django 4.2.16 on 2026-04-19 01:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_alter_loss_snapshot_verbose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Positive: customer owes the shop. Negative: shop holds credit for the customer (overpayment).', max_digits=14, verbose_name='current balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64, unique=True, verbose_name='phone or shipment number')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='label')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'customer phone',
                'verbose_name_plural': 'customer phones',
                'ordering': ['customer__name', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer', verbose_name='customer')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='sales.paymentmethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'customer payment',
                'verbose_name_plural': 'customer payments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=20, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always stored positive; entry_type signs it.', max_digits=14, verbose_name='amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='customers.customer', verbose_name='customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='customers.customerpayment', verbose_name='payment')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_entries', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'customer ledger entry',
                'verbose_name_plural': 'customer ledger entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='cust_ledger_recent_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customer_name_idx'),
        ),
    ]
