# Generated by Django 4.2.16 on 2026-04-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_customer_accounts_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerphone',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='phone or shipment number'),
        ),
        migrations.AddIndex(
            model_name='customerphone',
            index=models.Index(fields=['phone'], name='customer_phone_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerphone',
            constraint=models.UniqueConstraint(fields=('customer', 'phone'), name='customer_phone_unique_per_customer'),
        ),
    ]
