# Generated by Django 4.2.16 on 2026-04-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerphone_phone_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer', '-created_at'], name='cust_pay_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['-created_at'], name='cust_pay_created_desc'),
        ),
    ]
