# Generated by Django 4.2.27 on 2026-04-25 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0011_sale_sale_status_created_idx_and_more'),
        ('customers', '0003_customerpayment_cust_pay_recent_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='awaiting', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejected at')),
                ('reject_reason', models.TextField(blank=True, verbose_name='reject reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment_submissions_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment_submissions_created', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_submissions', to='customers.customer', verbose_name='customer')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment_submissions', to='sales.paymentmethod', verbose_name='payment method')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment_submissions_rejected', to=settings.AUTH_USER_MODEL, verbose_name='rejected by')),
            ],
            options={
                'verbose_name': 'customer payment submission',
                'verbose_name_plural': 'customer payment submissions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='cust_pay_sub_stat_idx')],
            },
        ),
    ]
