# Generated by Django 4.2.30 on 2026-07-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_salary_expense_link'),
        ('sales', '0014_employee_payroll'),
        ('customers', '0004_customer_payment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='employee_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments_received', to='employees.employeeprofile', verbose_name='employee recipient'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='paid_via_employee',
            field=models.BooleanField(default=False, help_text='Cash received by an employee on behalf of the shop; no payment method at entry.', verbose_name='payment to employee'),
        ),
        migrations.AddField(
            model_name='customerpaymentsubmission',
            name='employee_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment_submissions_received', to='employees.employeeprofile', verbose_name='employee recipient'),
        ),
        migrations.AddField(
            model_name='customerpaymentsubmission',
            name='paid_via_employee',
            field=models.BooleanField(default=False, help_text='Cash received by an employee on behalf of the shop; no payment method at entry.', verbose_name='payment to employee'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='sales.paymentmethod', verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='customerpaymentsubmission',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment_submissions', to='sales.paymentmethod', verbose_name='payment method'),
        ),
    ]
