# Generated by Django 4.2.30 on 2026-10-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_payment_recipients'),
        ('customers', '0005_customer_payment_via_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='payment_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='sales.paymentrecipient', verbose_name='payment recipient'),
        ),
        migrations.AddField(
            model_name='customerpaymentsubmission',
            name='payment_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_submissions', to='sales.paymentrecipient', verbose_name='payment recipient'),
        ),
    ]
