# Generated by Django 4.2.16 on 2026-04-20 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('mark_paid', 'Mark paid'), ('pay', 'Record payment'), ('adjust', 'Adjust balance'), ('write_off', 'Write off')], max_length=20, verbose_name='action')),
                ('model_label', models.CharField(help_text='Lowercased ``app_label.model_name`` of the affected row.', max_length=80, verbose_name='model')),
                ('object_id', models.CharField(blank=True, default='', max_length=64, verbose_name='object id')),
                ('object_repr', models.CharField(blank=True, default='', help_text='Snapshot of ``str(instance)`` so deletes stay meaningful.', max_length=255, verbose_name='object')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Per-field {old, new} for updates; arbitrary context otherwise.', verbose_name='changes')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_recent_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_idx'), models.Index(fields=['model_label', 'object_id'], name='audit_target_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_idx')],
            },
        ),
    ]
