# Generated by Django 4.2.30 on 2026-05-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_productline_default_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional; falls back to the line icon on the employee screen.', null=True, upload_to='icons/products/', verbose_name='package icon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, help_text='Examples: "100 GB", "200 GB". Leave empty if the line has only one package.', max_length=120, verbose_name='package'),
        ),
    ]
