# Generated by Django 4.2.27 on 2026-05-28 04:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_phone_refresh_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='estimated_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Used for SIM inventory valuation reports.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='estimated unit cost (SIM)'),
        ),
    ]
