# Generated by Django 4.2.16 on 2026-04-15 18:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=64, verbose_name='phone or shipment number')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='customer name')),
                ('payer_name', models.CharField(max_length=200, verbose_name='payer name')),
                ('sell_price_actual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='actual selling price')),
                ('cost_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cost price (snapshot)')),
                ('profit_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='profit (snapshot)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='marked paid at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_marked_paid', to=settings.AUTH_USER_MODEL, verbose_name='marked paid by')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.paymentmethod', verbose_name='payment method')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='companies.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('deduction', 'Deduction'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=20, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('reference_type', models.CharField(choices=[('sale', 'Sale'), ('manual', 'Manual'), ('opening_balance', 'Opening balance'), ('cancellation', 'Cancellation')], max_length=32, verbose_name='reference type')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='reference id')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'balance transaction',
                'verbose_name_plural': 'balance transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
