# Generated by Django 4.2.16 on 2026-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_paymentmethod_icon_remove_sale_customer_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['reference_number', '-created_at'], name='sale_ref_created_desc'),
        ),
    ]
