# Generated by Django 4.2.16 on 2026-04-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_reference_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_esim',
            field=models.BooleanField(default=False, verbose_name='eSIM sale'),
        ),
    ]
