# Generated by Django 4.2.16 on 2026-04-16 09:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_is_esim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sell_price_actual',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='actual selling price'),
        ),
    ]
