# Generated by Django 4.2.16 on 2026-04-16 09:18

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
from django.db.models import F


def backfill_zero_price_losses(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    Sale.objects.filter(sell_price_actual=0).update(loss_snapshot=F("cost_price_snapshot"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_sell_price_min_zero"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="loss_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="When selling price is 0, equals supplier cost recorded as an explicit loss; otherwise 0.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="loss from zero-price sale",
            ),
        ),
        migrations.RunPython(backfill_zero_price_losses, noop_reverse),
    ]
