# Generated by Django 4.2.16 on 2026-04-16 09:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_loss_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='loss_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='When selling price is 0, equals supplier cost recorded as an explicit loss; otherwise 0.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Loss'),
        ),
    ]
