# Generated by Django 4.2.16 on 2026-04-19 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_customer_accounts_initial'),
        ('sales', '0007_alter_loss_snapshot_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='sale',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_sales', to='customers.customerpayment', verbose_name='settled by payment'),
        ),
        migrations.AddField(
            model_name='sale',
            name='on_account',
            field=models.BooleanField(default=False, help_text='Customer credit sale: needs management approval and is settled later by a customer payment.', verbose_name='on account'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.paymentmethod', verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting approval'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
