# Generated by Django 4.2.16 on 2026-04-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_migrate_notpaid_to_on_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting approval'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('written_off', 'Written off')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
