# Generated by Django 4.2.27 on 2026-05-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sale_is_new_sim_sale_sim_consumed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sim_serial_or_iccid',
            field=models.CharField(blank=True, help_text='Optional. Links this sale to a tracked SIM card at approval time.', max_length=64, verbose_name='SIM serial or ICCID'),
        ),
    ]
