# Generated by Django 4.2.27 on 2026-05-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_employee_payroll'),
        ('sales', '0013_sim_phase3_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='employee_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_received', to='employees.employeeprofile', verbose_name='employee recipient'),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_via_employee',
            field=models.BooleanField(default=False, help_text='Cash received by an employee on behalf of the shop; no payment method at entry.', verbose_name='payment to employee'),
        ),
    ]
