# Generated by Django 4.2.30 on 2026-10-09 15:32

from django.db import migrations

LEGACY_COLUMN = "sim_stock_movement_id"


def drop_legacy_sim_stock_movement_column(apps, schema_editor):
    """Databases created before 0012 was edited still carry this FK column."""
    Sale = apps.get_model("sales", "Sale")
    table = Sale._meta.db_table
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        columns = {
            col.name for col in connection.introspection.get_table_description(cursor, table)
        }
    if LEGACY_COLUMN not in columns:
        return
    if connection.vendor == "sqlite":
        # SQLite cannot drop an indexed FK column in place; rebuilding the
        # table from the current model state leaves the column out.
        schema_editor._remake_table(Sale)
    else:
        schema_editor.execute(
            "ALTER TABLE %s DROP COLUMN %s CASCADE"
            % (schema_editor.quote_name(table), schema_editor.quote_name(LEGACY_COLUMN))
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_employee_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_new_sim',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sim_consumed_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sim_deducted_from',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sim_serial_or_iccid',
        ),
        migrations.RunPython(drop_legacy_sim_stock_movement_column, migrations.RunPython.noop),
    ]
