# Generated by Django 4.2.30 on 2026-10-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_sim_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sales.paymentmethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'payment recipient',
                'verbose_name_plural': 'payment recipients',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.paymentrecipient', verbose_name='payment recipient'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecipient',
            constraint=models.UniqueConstraint(fields=('payment_method', 'name'), name='uniq_recipient_name_per_method'),
        ),
    ]
